apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-malicious-file-scraper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      gw: web
  template:
    metadata:
      labels:
        gw: web
    spec:
      containers:
      - name: glasswallcrawler
        image: glasswallcrawler:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: glasswall-crawler-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    gw: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
